name: Build and deploy

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out and create a bundle
      - uses: action/checkout@v2
      - run: ./gradlew browserDistribution
